### ISSUE TITLE
Update the version in pypi

### ISSUE THREAD

**Issue by centralniak** [kneufeld/alkali#1]
Version `0.7.0` on pypi requires `six==1.10.0`, which makes it incompatible with such popular tools like Jupyter or Ipython.

**Comment by kneufeld** [comment]
I'm confused as `v0.7.0` specifies `six==1.10.0`

https://github.com/kneufeld/alkali/blob/8ddf2836f823f62f2f1c441d40407d17ee420163/requirements.txt

**Comment by centralniak** [comment]
What I mean, is that `v0.7.0` has `six` frozen at `1.10.0`, as you say.

The version on `master`, does not have `six` as a dependency. 

`six==1.10.0` is not compatible with latest versions of IPython or Jupyter.

**Comment by kneufeld** [comment]
Since version `0.7` alkali is python3 only so doesn't require `six`. The later versions on master remove `six` from the `requirements.txt` file entirely. 

I just remade my virtualenv at version `0.7` and `master` and ipython works in both. I think you'll have to paste some output to show me what you mean by _not compatible with latest versions of IPython_

**Comment by centralniak** [comment]
So I think it'd be good to update the latest version on pypi. 

I might have been imprecise; what I meant was that the dependencies of `alkali==0.7` were incompatible with the dependencies of latest `Jupyter`. 

E.g.:

```
pipenv shell --python 3.7
pipenv install alkali
pipenv install Jupyter
```

will fail:

```
Adding jupyter to Pipfile's [packages]…
Pipfile.lock (2b9902) out of date, updating to (431e88)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches six==1.10.0,>=1.11.0,>=1.5,>=1.9.0
Tried: 0.9.0, 0.9.1, 0.9.2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.0, 1.5.1, 1.5.1, 1.5.2, 1.5.2, 1.6.0, 1.6.0, 1.6.1, 1.6.1, 1.7.0, 1.7.0, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.8.0, 1.8.0, 1.9.0, 1.9.0, 1.10.0, 1.10.0, 1.11.0, 1.11.0, 1.12.0, 1.12.0
Skipped pre-versions: 1.0b1
There are incompatible versions in the resolved dependencies.
```

I was however wrong to imply, that the same happens if I install 'plain' IPython:

```
pipenv shell --python 3.7
pipenv install alkali
pipenv install ipython
```

will actually work. 

I'd simply suggest to update the latest version on pypi and my problem will be gone.

Cheers.

**Comment by kneufeld** [comment]
I've pushed a new version (`0.7.2`) to pypi that doesn't reference `six` at all, should solve your problem. You may have to delete and recreate your venv.

**Comment by centralniak** [comment]
And that worked :-) 

Perfect, thanks.
