### ISSUE TITLE
Pypi Package missing storage.py file

### ISSUE THREAD

**Issue by hpca01** [kneufeld/alkali#3]
Hi, sorry its me again! I just installed this package on my Manjaro OS with Pipenv.

```
     28 import os
     29 
---> 30 from .storage import Storage, JSONStorage
     31 
     32 import logging

ModuleNotFoundError: No module named 'alkali.storage'
```

Pipfile content:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
ipython = "*"
alkali = "==0.7.2"

[requires]
python_version = "3.7"
```
├── alkali
│   ├── database.py
│   ├── fields.py
│   ├── __init__.py
│   ├── manager.py
│   ├── memoized_property.py
│   ├── metamodel.py
│   ├── model.py
│   ├── peekorator.py
│   ├── query.py
│   ├── reify.py
│   ├── relmanager.py
│   ├── signals.py
│   └── utils.py

The link on PyPi: https://files.pythonhosted.org/packages/1d/83/6599d660fc467ea0cb740500e235189911e33b085da45472db3b7184167e/alkali-0.7.2.tar.gz#sha256=9b77f6d59e5b643d2df3384dbaf89ab0fb8820432ebef30a9cd5ed963ef5d79f

**Comment by kneufeld** [comment]
You're right that the `storage` subdir is missing from the provided link. I don't know how `pipenv` works but `pip install` works just fine... I'll have a look.

**Comment by kneufeld** [comment]
I've pushed version `0.7.3` which should fix the issue. Could you please verify and then close this issue?

Thanks for reporting this issue and your continued interest in alkali. 😄

**Comment by hpca01** [comment]
Hi, 

Thanks! it works!
